data:
    dataroot: data
    normal: False
    first_subsampling: 0.02
    train_size: 14016 # Number of shapes in the whole training set
    use_category: False
    category: "Airplane"
    pre_transforms:
        - transform: NormalizeScale
        - transform: GridSampling
          params:
              size: ${data.first_subsampling}
    train_transforms:
        - transform: RandomNoise
          params:
            sigma: 0.01
            clip: 0.05
        - transform: RandomScaleAnisotropic
          params:
            scales: [0.9,1.1]
        - transform: FixedPoints
          lparams: [1024]
    val_transforms:
        - transform: FixedPoints
          lparams: [1024]
training:
    batch_size: 2
    num_workers: 0
models:
    pointnet2:
        class_name: PointNet2
        conv_type: "dense"
        input_nc: 3
        in_feat: 16
        output_nc: 256
        num_layers: 3
    kpconv:
        class_name: KPConv
        conv_type: "partial_dense"
        input_nc: 0
        in_feat: 16
        output_nc: 256
        num_layers: 4
    rsconv:
        class_name: RSConv
        conv_type: "dense"
        input_nc: 3
        in_feat: 8
        output_nc: 256
        num_layers: 4
